# A toml config file for vire CI/CD (The other project I'm building)
# Note, Vire only reads the vire.toml in main.

[details]
framework = "eleventy"
package_manager = "npm"

[project]
node_version = "20"    # Node version
output_dir = "dist"   # Match this with the framework's output directory
dependencies="present" # Use present if it needs npm install. otherwise use absent

[deploy]
allow = ["main", "prod"] #Allowlist of branches

[deploy.main] #subtable, allow auto deployment for main
auto = true

[deploy.prod]
auto = false
manual_review = true
